import { translate } from './i18n.js';

const asTime = (milliseconds) => { const totalSeconds = Math.ceil(milliseconds / 1000); return `${String(Math.floor(totalSeconds / 60)).padStart(2, '0')}:${String(totalSeconds % 60).padStart(2, '0')}`; };
const asStopwatchTime = (milliseconds) => { const totalSeconds = Math.floor(milliseconds / 1000); const hours = Math.floor(totalSeconds / 3600); const minutes = Math.floor((totalSeconds % 3600) / 60); const seconds = totalSeconds % 60; return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`; };
const asClock = (timestamp, language) => new Intl.DateTimeFormat(language === 'zh' ? 'zh-CN' : 'en-US', { hour: '2-digit', minute: '2-digit', hour12: false }).format(timestamp);

export const createView = (root = document) => {
  const ids = ['language-toggle', 'timer-mode', 'remaining-time', 'progress-bar', 'current-task', 'task-name', 'start-work', 'start-break', 'pause-resume', 'stop-timer', 'reset-timer', 'work-minutes', 'break-minutes', 'auto-loop', 'stopwatch-auto-stop', 'alert-toggle', 'alert-volume', 'alert-volume-value', 'history-list', 'clear-history', 'session-count', 'rain-toggle', 'rain-volume', 'rain-volume-value', 'wallpaper-light', 'wallpaper-dark', 'wallpaper-rain', 'zen-toggle', 'zen-exit', 'stopwatch-time', 'stopwatch-start', 'stopwatch-stop', 'stopwatch-complete', 'stopwatch-reset'];
  const elements = Object.fromEntries(ids.map((id) => [id, root.getElementById(id)]));
  const applyLanguage = (language) => { root.documentElement.lang = language === 'zh' ? 'zh-CN' : language === 'ja' ? 'ja-JP' : 'en'; root.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = translate(language, element.dataset.i18n); }); root.querySelectorAll('[data-i18n-placeholder]').forEach((element) => { element.placeholder = translate(language, element.dataset.i18nPlaceholder); }); elements['language-toggle'].setAttribute('aria-label', language === 'zh' ? 'Switch language' : language === 'ja' ? '言語を切り替える' : '切换语言'); root.title = translate(language, 'title'); elements['zen-exit'].setAttribute('aria-label', translate(language, 'exitZenMode')); root.querySelectorAll('.language-option').forEach(opt => { opt.classList.toggle('active', opt.dataset.lang === language); }); };
  const renderTimer = ({ status, session, remainingMs }, language) => { const resolved = remainingMs ?? 25 * 60_000; const time = asTime(resolved); elements['remaining-time'].textContent = time; elements['remaining-time'].classList.toggle('is-running', status === 'running'); elements['remaining-time'].title = translate(language, 'remainingTitle', { time }); const progress = session ? Math.max(0, Math.min(100, resolved / session.durationMs * 100)) : 100; elements['progress-bar'].style.width = `${progress}%`; elements['start-work'].disabled = ['running', 'paused'].includes(status); elements['start-break'].disabled = ['running', 'paused'].includes(status); elements['pause-resume'].disabled = !['running', 'paused'].includes(status); elements['pause-resume'].textContent = translate(language, status === 'paused' ? 'resume' : 'pause'); elements['stop-timer'].disabled = !['running', 'paused'].includes(status); elements['reset-timer'].disabled = status === 'idle'; if (status === 'running') { elements['timer-mode'].textContent = translate(language, session.mode === 'work' ? 'workMode' : 'breakMode'); elements['current-task'].textContent = translate(language, 'currentTask', { task: session.task, start: asClock(session.startedAt, language), end: asClock(session.plannedEndAt, language) }); root.title = translate(language, 'tabTitle', { time }); } else if (status === 'paused') { elements['timer-mode'].textContent = translate(language, 'paused'); elements['current-task'].textContent = translate(language, 'pausedTask', { task: session.task }); } else { elements['timer-mode'].textContent = translate(language, status === 'completed' ? 'completed' : status === 'stopped' ? 'stopped' : 'ready'); if (status !== 'idle') elements['current-task'].textContent = ''; } };
  const renderHistory = (sessions, language, onDelete) => { elements['history-list'].replaceChildren(); elements['session-count'].textContent = sessions.filter(({ status }) => status === 'completed').length; if (!sessions.length) { const item = document.createElement('li'); item.textContent = translate(language, 'emptyHistory'); elements['history-list'].append(item); return; } sessions.forEach((session, index) => { const item = document.createElement('li'); item.className = session.status; const statusKey = session.status === 'completed' ? 'historyCompleted' : session.status === 'stopped' ? 'historyStopped' : 'historyAbandoned'; const content = document.createElement('span'); content.className = 'history-content'; content.textContent = `${session.task} · ${asClock(session.startedAt, language)}–${asClock(session.plannedEndAt, language)} · ${translate(language, statusKey)}`; const deleteBtn = document.createElement('button'); deleteBtn.className = 'history-delete'; deleteBtn.textContent = translate(language, 'deleteItem'); deleteBtn.setAttribute('aria-label', `${translate(language, 'deleteItem')} ${session.task}`); deleteBtn.addEventListener('click', () => onDelete(index)); item.append(content, deleteBtn); elements['history-list'].append(item); }); };
  const renderNoise = (enabled, volume) => { elements['rain-toggle'].checked = enabled; elements['rain-volume'].value = volume; elements['rain-volume-value'].textContent = `${Math.round(volume * 100)}%`; };
  const renderAlert = (enabled, volume) => { elements['alert-toggle'].checked = enabled; elements['alert-volume'].value = volume; elements['alert-volume-value'].textContent = `${Math.round(volume * 100)}%`; };
  const renderSettingsMode = (mode) => { root.getElementById('pomodoro-settings').hidden = mode !== 'pomodoro'; root.getElementById('stopwatch-settings').hidden = mode !== 'stopwatch'; };
  const renderWallpaper = (wallpaper) => { root.documentElement.classList.toggle('has-rain-wallpaper', wallpaper === 'rain'); root.documentElement.classList.toggle('has-dark-wallpaper', wallpaper === 'dark'); root.body.classList.toggle('has-rain-wallpaper', wallpaper === 'rain'); root.body.classList.toggle('has-dark-wallpaper', wallpaper === 'dark'); elements['wallpaper-light'].setAttribute('aria-pressed', String(wallpaper === 'light')); elements['wallpaper-dark'].setAttribute('aria-pressed', String(wallpaper === 'dark')); elements['wallpaper-rain'].setAttribute('aria-pressed', String(wallpaper === 'rain')); };
  const renderStopwatch = ({ status, elapsedMs }, language) => { const time = asStopwatchTime(elapsedMs); elements['stopwatch-time'].textContent = time; elements['stopwatch-start'].disabled = status === 'running'; elements['stopwatch-stop'].disabled = status === 'idle'; elements['stopwatch-complete'].disabled = status === 'idle'; if (status === 'running') root.title = translate(language, 'tabTitle', { time }); };
  return { elements, applyLanguage, renderTimer, renderHistory, renderNoise, renderAlert, renderSettingsMode, renderWallpaper, renderStopwatch };
};
